#!/usr/bin/perl -w



#!/usr/local/bin/perl -w

use strict;

while (1) {
    while (1) {
	my $line = <>;
	exit 0 unless defined $line;
	last if $line =~ /^\#if\s+SOLUTION/;
	print $line unless $line =~ /^\#define\s+SOLUTION/;
    }

    while (1) {
	my $line = <>;
	exit 0 unless defined $line;
	last if $line =~ /^\#endif\s+\/\*\s+SOLUTION/;
    }
}
